# Generated by Django 4.1.1 on 2022-09-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_works',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
