# Generated by Django 4.1.1 on 2022-09-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notation', '0003_tb_works_time2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_works',
            old_name='time2',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='tb_works',
            name='time',
        ),
    ]
